// Content script: captures a cleaned version of the page HTML and sends it to the background worker.
// Also executes form-fill commands generated by the backend.

import type { FormFillCommand } from '../types/loan.js';

function captureCleanHtml(): string {
  const clone = document.documentElement.cloneNode(true) as HTMLElement;

  // Remove tags that add noise but no useful text content
  const noiseTags = ['script', 'style', 'svg', 'img', 'video', 'audio', 'iframe', 'noscript', 'canvas'];
  for (const tag of noiseTags) {
    clone.querySelectorAll(tag).forEach((el) => el.remove());
  }

  // Remove hidden elements to reduce payload size
  clone.querySelectorAll('[aria-hidden="true"], [hidden]').forEach((el) => el.remove());

  // Cap at 400 KB to stay well within Claude's context limit
  const html = clone.outerHTML;
  return html.length > 400_000 ? html.slice(0, 400_000) : html;
}

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === 'PING') {
    sendResponse({ alive: true });
    return true;
  }

  if (message.type === 'CAPTURE_HTML') {
    try {
      const html = captureCleanHtml();
      sendResponse({ success: true, html, sourceUrl: window.location.href });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      sendResponse({ success: false, error: msg });
    }
    return true;
  }

  if (message.type === 'EXECUTE_COMMANDS') {
    try {
      executeFormFillCommands(message.commands as FormFillCommand[]);
      sendResponse({ success: true });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      sendResponse({ success: false, error: msg });
    }
    return true;
  }
});

function executeFormFillCommands(commands: FormFillCommand[]): void {
  for (const cmd of commands) {
    const el = document.querySelector(cmd.selector);
    if (!el) {
      console.warn(`[loan-fill] No element found for selector: ${cmd.selector}`);
      continue;
    }

    if (cmd.action === 'fill') {
      (el as HTMLInputElement).value = cmd.value ?? '';
      el.dispatchEvent(new Event('input', { bubbles: true }));
      el.dispatchEvent(new Event('change', { bubbles: true }));
    } else if (cmd.action === 'select') {
      (el as HTMLSelectElement).value = cmd.value ?? '';
      el.dispatchEvent(new Event('change', { bubbles: true }));
    } else if (cmd.action === 'click') {
      (el as HTMLElement).click();
    } else if (cmd.action === 'check') {
      (el as HTMLInputElement).checked = cmd.value !== 'false';
      el.dispatchEvent(new Event('change', { bubbles: true }));
    }
  }
}
