import type { CarData } from './types.js';

const CARS: CarData[] = [
  {
    vin: '1HGBH41JXMN109186',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    trim: 'EX',
    price: 24500,
    priceCurrency: 'USD',
    mileage: 18500,
    mileageUnit: 'mi',
    color: 'Blue',
    transmission: 'automatic',
    fuelType: 'gasoline',
    engine: '1.5L Turbo 4-Cylinder',
    bodyStyle: 'Sedan',
    driveType: 'FWD',
    doors: 4,
    condition: 'used',
    stockNumber: 'HC-2022-001',
    description: '2022 Honda Civic EX with low mileage, one owner, clean carfax.',
    sourceUrl: 'https://inventory.example.com/cars/HC-2022-001',
    extractedAt: '2026-03-10T00:00:00.000Z',
  },
  {
    vin: '2T1BURHE0JC049587',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    trim: 'LE',
    price: 21900,
    priceCurrency: 'USD',
    mileage: 32000,
    mileageUnit: 'mi',
    color: 'White',
    transmission: 'automatic',
    fuelType: 'gasoline',
    engine: '1.8L 4-Cylinder',
    bodyStyle: 'Sedan',
    driveType: 'FWD',
    doors: 4,
    condition: 'used',
    stockNumber: 'TC-2021-002',
    description: '2021 Toyota Corolla LE, excellent condition, no accidents.',
    sourceUrl: 'https://inventory.example.com/cars/TC-2021-002',
    extractedAt: '2026-03-10T00:00:00.000Z',
  },
  {
    vin: '1FTFW1ET5DFC10312',
    make: 'Ford',
    model: 'F-150',
    year: 2023,
    trim: 'XLT',
    price: 42000,
    priceCurrency: 'USD',
    mileage: 8200,
    mileageUnit: 'mi',
    color: 'Black',
    transmission: 'automatic',
    fuelType: 'gasoline',
    engine: '2.7L EcoBoost V6',
    bodyStyle: 'Truck',
    driveType: '4WD',
    doors: 4,
    condition: 'used',
    stockNumber: 'FF-2023-003',
    description: '2023 Ford F-150 XLT 4WD, like new, loaded with options.',
    sourceUrl: 'https://inventory.example.com/cars/FF-2023-003',
    extractedAt: '2026-03-10T00:00:00.000Z',
  },
  {
    vin: 'WBAJB0C51BC461750',
    make: 'BMW',
    model: '5 Series',
    year: 2020,
    trim: '530i',
    price: 38500,
    priceCurrency: 'USD',
    mileage: 41000,
    mileageUnit: 'mi',
    color: 'Silver',
    transmission: 'automatic',
    fuelType: 'gasoline',
    engine: '2.0L Turbo Inline-4',
    bodyStyle: 'Sedan',
    driveType: 'RWD',
    doors: 4,
    condition: 'used',
    stockNumber: 'BM-2020-004',
    description: '2020 BMW 530i, well maintained, full service history.',
    sourceUrl: 'https://inventory.example.com/cars/BM-2020-004',
    extractedAt: '2026-03-10T00:00:00.000Z',
  },
  {
    vin: '5YJSA1E26MF437989',
    make: 'Tesla',
    model: 'Model S',
    year: 2021,
    trim: 'Long Range',
    price: 72000,
    priceCurrency: 'USD',
    mileage: 22000,
    mileageUnit: 'mi',
    color: 'Red',
    transmission: 'automatic',
    fuelType: 'electric',
    engine: 'Dual Motor Electric',
    bodyStyle: 'Sedan',
    driveType: 'AWD',
    doors: 4,
    condition: 'used',
    stockNumber: 'TS-2021-005',
    description: '2021 Tesla Model S Long Range AWD, Autopilot, full self-driving capability.',
    sourceUrl: 'https://inventory.example.com/cars/TS-2021-005',
    extractedAt: '2026-03-10T00:00:00.000Z',
  },
];

export function getCars(): CarData[] {
  return CARS;
}
